server:
  port: 8082

spring:
  application:
    name: subscription-engine


  docker:
    compose:
      enabled: false


  config:
    import: optional:file:.env.local[.properties]



  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


app:
  cors:
    allowed-origins: "*"
    allow-credentials: false


payment:
  nomba:
    base-url: ${NOMBA_BASE_URL}
    account-id: ${NOMBA_PARENT_ACCOUNT_ID}
    subaccount-id: ${NOMBA_SUBACCOUNT_ID}
    client-id: ${NOMBA_CLIENT_ID}
    client-secret: ${NOMBA_CLIENT_SECRET}
    webhook-secret: ${NOMBA_WEBHOOK_SECRET:}
    sub-account:
      enabled: false

http:
  connect-timeout-ms: 5000
  response-timeout-ms: 15000